# This file was generated by GoReleaser. DO NOT EDIT.
class Hellohomebrew < Formula
  desc "BEW 2.5 - Homebrew Hello World"
  homepage "https://github.com/droxey/homebrew-hellohomebrew"
  version "1.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/droxey/hellohomebrew/releases/download/v1.0.5/hellohomebrew_1.0.5_macOS-64bit.tar.gz"
    sha256 "ebf11c26770e7776a0273e0d29972fda5d46035cb75d4612e61cc2744d84e498"
  elsif OS.linux?
  end

  def install
    bin.install "hellohomebrew"
  end
end
